[project]
name = "myla-ts"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "aiohttp>=3.13.2",
    "claude-agent-sdk>=0.1.6",
    "python-dotenv>=1.2.1",
    "slack-bolt>=1.26.0",
]
